app_name=ESTACAOPONTO
base_intranet_url=http://localhost:8080/intranet
#base_intranet_url=http://www.tjpi.jus.br/intranet
tela_cheia=true
bloqueio_tela=false
# 1-9
nivel_seguranca_leitor=8
baixa_foto=false