
import com.nitgen.SDK.BSP.NBioBSPJNI;
import com.nitgen.SDK.BSP.NBioBSPJNI.FIR_PAYLOAD;
import com.nitgen.SDK.BSP.NBioBSPJNI.FIR_TEXTENCODE;
import com.nitgen.SDK.BSP.NBioBSPJNI.INPUT_FIR;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anderson Soares
 */
public class TesteUI extends javax.swing.JFrame {

    
    private static NBioBSPJNI bsp;
    private static NBioBSPJNI.DEVICE_ENUM_INFO deviceEnumInfo;
    private static NBioBSPJNI.WINDOW_OPTION winOption;
    
     /**
     * faz a captura da digital e retorna a mesma em formato texto
     * caso nao haja erro
     * @return digital formato texto(String)
     */
    public FIR_TEXTENCODE capturarDigital() {
        abrirLeitor();
        
        NBioBSPJNI.FIR_HANDLE hSavedFIR = bsp.new FIR_HANDLE();
       
        bsp.Capture(NBioBSPJNI.FIR_PURPOSE.VERIFY, hSavedFIR, -1, null, winOption);
        //bsp.Capture(hSavedFIR);
        
        if(bsp.IsErrorOccured()) {
            throw new RuntimeException("Nao foi possivel achar o padrao de uma digital");
        } else {
            //Recupera a digital em formato de texto
            NBioBSPJNI.FIR_TEXTENCODE textSavedFIR = bsp.new FIR_TEXTENCODE();
            bsp.GetTextFIRFromHandle(hSavedFIR, textSavedFIR);
            
            
            
            return textSavedFIR;
        }
    }

    /**
     * abre conexao com o leitor de digital
     */
    private void abrirLeitor() {
        bsp = new NBioBSPJNI(); // Declare NBioBSPJNI Class Object
        
        deviceEnumInfo = bsp.new DEVICE_ENUM_INFO();
        winOption = bsp.new WINDOW_OPTION();
        
        winOption.WindowStyle = NBioBSPJNI.WINDOW_STYLE.INVISIBLE;
        //winOption.WindowStyle |= NBioBSPJNI.WINDOW_STYLE.NO_WELCOME;
        
        winOption.FingerWnd = fpWindow;
        
        // Enumerate device
        bsp.EnumerateDevice(deviceEnumInfo);
        
        bsp.OpenDevice(deviceEnumInfo.DeviceInfo[0].NameID, deviceEnumInfo.DeviceInfo[0].Instance);
        
    }

    /**
     * Fecha conexao com o leitor de digital
     */
    private void fecharLeitor() {
        bsp.CloseDevice(deviceEnumInfo.DeviceInfo[0].NameID,deviceEnumInfo.DeviceInfo[0].Instance);
        deviceEnumInfo = null;
        bsp = null;
    }
    
    /**
     * Creates new form TesteUI
     */
    public TesteUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fpWindow = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(fpWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(fpWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TesteUI teste = new TesteUI();;
                teste.setVisible(true);
                
                
                
                
                 //Captura a primeira digital
                FIR_TEXTENCODE textSavedFIR = teste.capturarDigital();
                System.out.println("Digital 1 formato texto: "+textSavedFIR.TextFIR);

                NBioBSPJNI.INPUT_FIR inputFIR = bsp.new INPUT_FIR();
                inputFIR.SetTextFIR(textSavedFIR);

                //Captura a segunda digital
                FIR_TEXTENCODE textCapturedFIR = teste.capturarDigital();
                System.out.println("Digital 2 formato texto: "+textCapturedFIR.TextFIR);

                NBioBSPJNI.INPUT_FIR inputFIR2 = bsp.new INPUT_FIR();
                inputFIR2. SetTextFIR(textCapturedFIR);


                Boolean bResult = new Boolean(false);
                NBioBSPJNI.FIR_PAYLOAD payload = bsp.new FIR_PAYLOAD();


                bsp.VerifyMatch(inputFIR, inputFIR2, bResult, payload);
                if (bsp.IsErrorOccured() == false) {
                    if (bResult)
                        System.out.println("Verify OK - Payload: " + payload.GetText());
                    else
                        System.out.println("Verify Failed");
                }
                
                teste.fecharLeitor();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas fpWindow;
    // End of variables declaration//GEN-END:variables
}
